### ISSUE TITLE
Do you have support for lsp?

### ISSUE THREAD

**Issue by SamPosh** [feoh/git_dotfiles#1]
I would like to do rename, go to definition and find all references.

In astrovim i am seeing them but it seems very hard to grasp it. Do you have any similar thing in Kickstart.nvim 

https://github.com/AstroNvim/AstroNvim/blob/8d142661f7346789f71ca220623dd199371cf74d/lua/astronvim/utils/lsp.lua

**Comment by feoh** [comment]
The easiest way to install LSPs with kickstart.nvim is via Mason.

Type :Mason and you'll be presented with a nice UI from which you can install the various language servers.

Also, thanks for the report but this isn't really an open source project per-se, just me putting my dot files here in case someone might find them useful :)

**Comment by SamPosh** [comment]
sorry bro
